In [1]:
#importing numpy library
import numpy as np

In [4]:
#creating an list
a=[12,3,323,13,1,39]
print(a)
print(type(a))

[12, 3, 323, 13, 1, 39]
<class 'list'>


In [5]:
#converting a list into numpy array
a=np.array(a)#this is an 1D array i.e arrat with single row
print(a)
print(type(a))

[ 12   3 323  13   1  39]
<class 'numpy.ndarray'>


In [16]:
print('Max number in array=',max(a))#max number
print('Min number in array=',min(a))#min number
print('Sum of all numbers in array=',sum(a))#sum of all numbers
print('Mean of numbers in array=',a.mean())#mean
print('Shape of array=',a.shape)#min number

Max number in array= 323
Min number in array= 1
Sum of all numbers in array= 391
Mean of numbers in array= 65.16666666666667
Shape of array= (6,)


In [22]:
#creating random numpy array

In [23]:
print(np.zeros((3,4))) #creating array with all zero elements

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
print(np.ones((2,2))) #creating array with all 1 elements

[[1. 1.]
 [1. 1.]]


In [27]:
print(np.full((5,3),5)) #creating an array filled with 5

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [29]:
print(np.eye((2))) #creating an identity matrix

[[1. 0.]
 [0. 1.]]


In [30]:
np.random.randint(1, 10, (2, 4)) #creating an random array from numbers 1 to 10

array([[2, 2, 5, 6],
       [1, 5, 2, 3]])

In [37]:
#creating an 1D array
b= np.array([1,2,3])
print("1D array:",b)
print("Shape:", b.shape)
print("Dimensions:", b.ndim)

1D array: [1 2 3]
Shape: (3,)
Dimensions: 1


In [38]:
#creating an 2D array
d=np.array([[1,2,3],[4,5,6]])
print("2D array:", d)
print("Shape:", d.shape)
print("Dimensions:", d.ndim)

2D array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2


In [31]:
c = np.array([[[1, 2, 3],
               [4, 5, 6]],

              [[7, 8, 9],
               [10, 11, 12]]])
print(c)
print("Shape:", c.shape)
print("Dimensions:", c.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Dimensions: 3


In [39]:
#Array Indexing and Slicing

In [44]:
m1 = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
m1[0,0] #first row first column

1

In [47]:
m1[0] #first row

array([1, 2, 3, 4])

In [51]:
m1[0:3,1:2] #first row entire second column

array([[ 2],
       [ 6],
       [10]])

In [57]:
c = np.array([[[1, 2, 3],
               [4, 5, 6]],
              [[7, 8, 9],
               [10, 11, 12]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
print(c[0, 1, 2])   # Depth 0, row 1, col 2 -> 6
print(c[1, :, :])   # Entire 2nd "matrix"
print(c[:, 0, :])   # First row from each depth

6
[[ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [7 8 9]]


In [58]:
#bollean indexing
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr > 10])    # Elements greater than 10 
print(arr[arr % 2 == 0])# Even elements 

[15 20 25]
[10 20]


In [59]:
#array opearations

In [63]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[4,3,1],[2,6,1]])
print('Martix A:',a)
print('Matrix B:',b)

Martix A: [[1 2 3]
 [4 5 6]]
Matrix B: [[4 3 1]
 [2 6 1]]


In [64]:
print(a+b) #addition of arrays

[[ 5  5  4]
 [ 6 11  7]]


In [66]:
print(a-b) #Substraction of array

[[-3 -1  2]
 [ 2 -1  5]]


In [67]:
print(a*b) #Multiplication

[[ 4  6  3]
 [ 8 30  6]]


In [68]:
print(2*a)#scalar multiplication

[[ 2  4  6]
 [ 8 10 12]]


In [69]:
#applying mathematical functions on arrays
arr = np.array([1, 4, 9, 16])
arr

array([ 1,  4,  9, 16])

In [71]:
print(np.sqrt(arr))   #square root of each element

[1. 2. 3. 4.]


In [73]:
print(np.exp(arr))    # exponential of each element

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [74]:
print(np.sin(arr))    # sine of each element

[ 0.84147098 -0.7568025   0.41211849 -0.28790332]


In [75]:
#reshaping array

In [80]:
arr1=np.random.randint(1,10,9) #we have created an array of 9 elements
arr1

array([9, 9, 2, 2, 3, 1, 2, 5, 7])

In [82]:
reshape=arr1.reshape(3,3) #reshaping array to 3*3 matrix
reshape

array([[9, 9, 2],
       [2, 3, 1],
       [2, 5, 7]])

In [84]:
print(reshape.ravel())   

[9 9 2 2 3 1 2 5 7]


In [85]:
#conactination of arrays

In [95]:
a=np.array([[1,2],[3,4]])
b=np.array([5,6])
c=np.vstack((a,b)) #vertical stack
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [98]:
a=np.array([1,2,3])
b=np.array([5,6,7])
c=np.vstack((a,b)) #horizontal stack
print(c)

[[1 2 3]
 [5 6 7]]


In [99]:
arr=np.array([[1,2],[3,4]]) #split into 2 parts column wise
print(np.split(arr, 2, axis=1)) 

[array([[1],
       [3]]), array([[2],
       [4]])]


In [100]:
arr=np.array([[1,2],[3,4]]) #split into 2 parts array wise
print(np.split(arr, 2, axis=0)) 

[array([[1, 2]]), array([[3, 4]])]


In [103]:
arr = np.arange(6).reshape(2, 3)
print(arr)
print(arr.T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [107]:
#Matrix Operations and Linear Algebra

In [108]:
#dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))   # 1*4 + 2*5 + 3*6 = 32

32


In [109]:
#Matrix Multiplication
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
print(np.matmul(A, B))
#how it works = 1*5 + 7*2 = 19 

[[19 22]
 [43 50]]


In [111]:
#linear algebra operations
print(np.linalg.det(A))   # Determinant of matrix A

-2.0000000000000004


In [112]:
print(np.linalg.inv(A)) #inverse of matrix A

[[-2.   1. ]
 [ 1.5 -0.5]]


In [114]:
#eigen values and eigen vectors 
values, vectors = np.linalg.eig(A) 
print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [119]:
#Solve system of equations: 2x + 3y = 5, x – y = 2.
A=np.array([[2,3],[1,-1]])
B=np.array([5,2])
C=np.linalg.solve(A,B)
print('X=',C[0])
print('Y=',C[1])

X= 2.2
Y= 0.2
